### ISSUE TITLE
[TYPE 2] [Enable 2FA/SAML methods]

### ISSUE THREAD

**Issue by jpanczel** [tableau/server-client-python#1008]
## Summary
It would be great if as a user I could authenticate to TSC even when using SSO or 2FA.

## Request Type
If you know, say which of these types your request is in the title, and follow the suggestions for that type when writing your description.

****Type 2: add a REST API and support it in tsc.****
In the Web UI it is possible to log in with SSO and user and pw, even with 2FA. These authentication methods are helping companies to keep their data safe.

## Description
Currently the only option to authenticate to TSC if we are using 2FA or SAML is to use PAT, but as far as I know there can't be parallel connections made to Tableau using the same PAT, which becomes problematic if I want to trigger jobs with the Airflow Tableau Operator.

**Comment by gibz104** [comment]
I would also like to see this functionality.

Our organization uses SSO authentication with Tableau Server and the only option is to use TSC with a PAT.  There is no way to authenticate with TSC using username/password + SSO/SAML.

**Comment by jacalata** [comment]
My understanding is that this feature wasn't included because 2FA requires manual interaction at the time of use, which doesn't make sense for a programmatic interface. Can you describe how you'd use it?

**Comment by gibz104** [comment]
We are trying to achieve the same actitivity which is described above in the `Description` of the initial issue.  Which is, we would like to use a cloud orchestration tool (like Airflow) to schedule datasources to be published to Tableau Server.  We use SSO/SAML with our instance of Tableau Server.  Therefore, we are forced to use PAT for authentication, but PAT does not support concurrent calls / jobs being run.  

So we are a bit stuck...  we cannot use username/pass for concurrent calls because we have SSO setup and we cannot use PAT because we cannot have concurrent calls using PAT. 

It seems as though there is not a solution for our SSO setup?  To your point, we would not be able to use a solution that requires manual interaction at run time as these jobs would be trigger and ran using an orchestration tool.

**Comment by ordonezf** [comment]
> So we are a bit stuck... we cannot use username/pass for concurrent calls because we have SSO setup and we cannot use PAT because we cannot have concurrent calls using PAT.

We are in the same boat, removing concurrency would be a huge hit on performance and MFA will be enforced in like 2 weeks 😕

**Comment by jacalata** [comment]
There isn't going to be a solution for that in the next couple of weeks, but if MFA will break something you should definitely get in touch with Support or your Account Manager if you have one to talk about how we can help.

**Comment by ordonezf** [comment]
> There isn't going to be a solution for that in the next couple of weeks, but if MFA will break something you should definitely get in touch with Support or your Account Manager if you have one to talk about how we can help.

We kinda found a workaround for now, but we will definitely get int touch with support. Thanks!

**Comment by ordonezf** [comment]
> > 
> 
> > > There isn't going to be a solution for that in the next couple of weeks, but if MFA will break something you should definitely get in touch with Support or your Account Manager if you have one to talk about how we can help.
> > 
> > 
> > We kinda found a workaround for now, but we will definitely get int touch with support. Thanks!
> 
> What workaround did you find?

We created a bunch of PAT's and made a class that is in charge of distributing them. When the pat is in use we mark it as busy in a table and when it's done we set it back to available

**Comment by lgwacker** [comment]
Bump +1

**Comment by jacalata** [comment]
This is the same request as #717
