### ISSUE TITLE
Paginated query logic is incorrect

### ISSUE THREAD

**Issue by dion-gdn** [tableau/server-client-python#1134]
**Describe the bug**
Logic of [paginated_query](https://github.com/tableau/server-client-python/blob/83e1069520669ad18f2cfca384bc74784c3bb75a/tableauserverclient/server/endpoint/metadata_endpoint.py#L92) function in [metadata_endpoint.py](https://github.com/tableau/server-client-python/blob/master/tableauserverclient/server/endpoint/metadata_endpoint.py) is incorrect. Pagination in GraphQL should use `cursor` inside `edges` and not `endCursor` inside `nodes.pageInfo` because `endCursor` corresponds to the **[last cursor of all items](https://github.com/api-platform/api-platform/issues/530#issuecomment-359749847)**. Because of that, the `endCursor` won't change and the next subsequent query will always return the exact same data. Obviously this inevitably resulted in an infinite loop because the `hasNextPage` value is always true.

Please note that I don't know if this behavior is intended, because the data type that I'm trying to query don't have edges. But do please let me know. Thank you.

**Versions**
Details of your environment, including:
 - ~Tableau Server version~ (using Tableau Online)
 - Python 3.10.8
 - TSC 0.23

**To Reproduce**
1. Set logger level to DEBUG
2. Execute `paginated_query`
```python
data = server.metadata.paginated_query(
        query,
        variables={"first": 1},
        abort_on_error=True
)
```
3. Observe log printing the same cursor a million of times

**Results**
No error code or message but the behavior is incorrect.

**Comment by dion-gdn** [comment]
Sorry, I'm the one who make mistake here. Thanks anyway.

**Comment by asluzh** [comment]
Hello, I'm facing the same issue with **paginaged_query**() method.
Could you provide more context about the resolution, and is there a proper method to perform paginated queries with Metadata API?
It seems that the code in paginated_query() is not correct, since it's using the "endCursor" attribute to provide the next page's "afterToken" value. If the "endCursor" is pointing to the last cursor of all items from a query, this logic will not work. Or am I making a thinking mistake here?
Thanks for your help.
