### ISSUE TITLE
Failed to download image for view in workbook that has missing embedded credentials in another view.

### ISSUE THREAD

**Issue by mauropasi** [tableau/server-client-python#1211]
**Describe the bug**
When attempting to download the image for a view in a workbook, the client returns an error if the workbook has missing embedded credentials in another view (even if the image for that view is not being downloaded)

**Versions**
Details of your environment, including:
 - Tableau Server version: 2022.3
 - Python version: 3.9.16
 - TSC library version: 0.24

**To Reproduce**
with SERVER.auth.sign_in():
    view = SERVER.views.get_by_id()
    print(view.name, view.id)
    image_req_option = TSC.ImageRequestOptions(
        imageresolution=TSC.ImageRequestOptions.Resolution.High, maxage=1)
    SERVER.views.populate_image(view, image_req_option)
    file_name = 'image.jpg'
    
    with open('/tmp/' + file_name, "wb") as image_file:
                        image_file.write(view.image)

**Results**
ServerResponseError: 

	400074: Bad Request
		There was a problem querying the image for view

**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by jacalata** [comment]
Hmm, I'm not actually sure if I expect that to work or not. I'll look into this.

**Comment by jacalata** [comment]
I'm afraid this is the expected behavior: the workbook itself requires all the connected datasources to be authorized before you can load the views. Unfortunately that means that until https://github.com/tableau/server-client-python/issues/1201 is supported, you can't download any of the views in a workbook that has a datasource requiring credentials.
