### ISSUE TITLE
server.tasks ValueError: name must be defined.

### ISSUE THREAD

**Issue by segunskl** [tableau/server-client-python#1237]
**Describe the bug**
I can use this code to get all tasks in my tableau online since last year. But today this code return error like this. How to fix the error?

**Versions**
Details of your environment, including:
 - Tableau Server version (or note if using Tableau Online) > Tableau Online
 - Python version > 3.8
 - TSC library version > 0.25

**To Reproduce**
Steps to reproduce the behavior. Please include a code snippet where possible.
```
server = TSC.Server(TABLEAU_URL, use_server_version=True)
server.auth.sign_in(tableau_auth)
all_tasks = list(TSC.Pager(server.tasks))
```

**Results**
What are the results or error messages received?

![image](https://github.com/tableau/server-client-python/assets/102509827/2ae1df9e-ead6-4f15-9354-259c13ea57ff)

**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by stav-hacohen** [comment]
We are facing the same issue. Seems like a change in tableau backend. Please advice.

**Comment by pavel-sho** [comment]
seems like element object <Element '{http://tableau.com/api}schedule' at 0x7fdda840e1d0> ,
returned object 
```python
schedule_xml.items()
[('frequency', 'Monthly'), ('nextRunAt', '2023-06-01T09:00:00Z')]
```

the name is not presented in the response from tableau.com

**Comment by jacalata** [comment]
Yes, it is a server change, the fix will be to remove the non-nullable attribute so the library accepts the new object.

**Comment by pavel-sho** [comment]
Hi @jacalata, is there a way to prioritize this bug or at least getting some ETA for a fix?

Thanks

**Comment by pavel-sho** [comment]
Hi @SQLShortReads, you right, the purpose we use tasks service, is to check which workbook_id / datasource_id has incremental refresh, if there is any we trigger it, as part of orchestration we do via Airflow, currently Tableau supports only full refresh when using their Airflow Operator, supporting incremental refresh require some dirty tricks.

**Comment by austinpeters-gohealthuccom** [comment]
Hey all, because I keep getting the short end with Tableau Support (a repeat trend for my org, how about you all?), I made a hotfix for this. Check the PR out above, there's only a few small changes you need to do to fix this bug. 

If you need to apply it yourself to patch a pip installed copy and don't know how to make a modified package from a git yourself, here's my lazy approach:

1. in windows file explorer, go to **%appdata%\Python\Python310\site-packages\tableauserverclient\models\**
2. (if you're not using Python 3.10 or have it installed elsewhere, change the URI as needed)
3. Replace the schedule_item.py file there with the file from the pull request.
4. Restart whatever code/program you're running, so your python environment refreshes.

**Comment by SQLShortReads** [comment]
Has anyone been able to successfully retrieve data on scheduled flow tasks? As previously stated, only extractRefresh tasks seem to be returned by server.tasks.
