### ISSUE TITLE
Update Datasource Connection

### ISSUE THREAD

**Issue by MouradHRM** [tableau/server-client-python#190]
The REST API supports the feature "Update Datasource Connection" but there is not an implementation in server-client-python for that.
And I try to set new connection settings to datasources freshly published.
There is an analog feature for workbooks and I'd like to propose an implementation similar to it.

**Comment by MouradHRM** [comment]
I could not find the test of update workbook connection. I'm not sure how I can implement the test of update datasource connection

**Comment by RussTheAerialist** [comment]
#253  adds this ability and unifies the api around this.

**Comment by bheem123** [comment]
I tested the update_connection.py on my server version 2018.2, and it does not work. No error,  but nothing is updated on server. Did this work for anyone?

**Comment by tdelosh** [comment]
I also can run the code, but nothing is updated. Does anyone have information on this?

**Comment by tdelosh** [comment]
Figured this out. Finally. This does nothing (paraphrasing):

wb.connections[i].username = 'new_username'
wb.connections[i].password = 'new_password'

Because the connection_items fetched by server.workbooks.populate_connections() are not writable.

I know next to nothing about Python, but this works:

from copy import deepcopy
# as you're iterating though the connections using index var i:
conn_copy = deepcopy(wb.connections[i])
conn_copy.username = 'dracula'
conn_copy.password = 'mypwd'
conn_copy.embed_password = True
server.workbooks.update_connection(wb, conn_copy)

Not sure a deep copy is necessary, but I'm not going to mess with it.
