### ISSUE TITLE
python client triggered refresh not refreshing dashboard

### ISSUE THREAD

**Issue by earthmancash2** [tableau/server-client-python#352]
Hey there, I followed the [refresh script](https://github.com/tableau/server-client-python/blob/master/samples/refresh.py) to refresh the data source and workbook for one of our dashboards.

```

import tableauserverclient as TSC

tableau_auth = TSC.TableauAuth('username', 'password', site_id="mysite")
server = TSC.Server('server_url', use_server_version=True)

print(server.version)

with server.auth.sign_in(tableau_auth):
    data_source_id = '[datasource_id]'
    resource = server.datasources.get_by_id(data_source_id)
    results = server.datasources.refresh(resource)
   
    # Comment this out to do the same by workbook 
    #workbook_id = '[workbook_id]'
    #results = server.workbooks.refresh(workbook_id)
    #print(results)
    
    myJobId = 'myjobid'
    jobinfo = server.jobs.get(myJobId)

    print(jobinfo)
```

The script is able to call the refresh() functions, and the results object gives me something that looks good:

`<Job#12345 RefreshExtract created_at(2018-10-29 15:22:15+00:00) started_at(None) completed_at(None) progress (None) finish_code(-1)>`

It eventually becomes `<Job#12345 RefreshExtract created_at(2018-10-29 15:22:15+00:00) started_at(2018-10-29 15:22:15+00:00) completed_at(2018-10-29 15:22:15+00:00) progress (100) finish_code(1)>`

However, when I open my dashboard in the browser, it still has not refreshed! We are using Tableau Online (not server), but all of the commands seem to give API responses that looked good.

Do you know what is going on?

**Comment by nishantnath** [comment]
It is often a caching issue. It would get fixed by hitting the refresh button on the dashboard. Some approaches for a workaround that has worked for me in the past: 
* Issuing a request.get('<server>/t/<project>/views/<viewUrl>?:refresh=yes')
* Simulating a refresh button click using selenium
* I have seen usages with tableau JS API - simulating refresh as an embedded view on a webpage

Because caching is  whimsical - its difficult to say for sure what really works but here are my thoughts:
The 1st way works 90% of the times (my guess is heavier dashboards don't refresh as easily) while the 2nd way works almost 100% of the time but more work to implement and maintain.
Can't say much about the 3rd method as I personally haven't tested this.

It is frustrating that the python client doesn't support this feature yet.

**Comment by irwando** [comment]
As TSC seems to be working correctly I would agree, either an issue with caching or something else (filtering in the Viz perhaps).  

No commentary in months on this, so closing.  If you're still having issues please let us know.
