### ISSUE TITLE
Add support for Favorites

### ISSUE THREAD

**Issue by benlower** [tableau/server-client-python#39]
Once the REST API enables GET Favorites we can add complete support for Favorites.

**Comment by jorwoods** [comment]
The REST API supports GET Favorites with API version 2.5.

**Comment by jorwoods** [comment]
I tried to implement this myself, but ran into difficulties due to the fact that the favorites API returns views, datasources, workbooks, and projects in a single API call. Combine that with inconsistencies in each Item's `_set_values` method, it was much more difficult to implement than I was expecting. I have a branch in my repo with the attempt if anyone wants to build off of that.

**Comment by jacalata** [comment]
I'm going to call this done, although I think there are now new types that can be returned as favorites. We can add that later.
