### ISSUE TITLE
Roles do not match new version of Tableau Server

### ISSUE THREAD

**Issue by elambrou5** [tableau/server-client-python#398]
I am trying to write a script to assign roles to new users and when trying Interactor and Viewer it sets the role to Unlicensed. Publisher gives me Explorer(can publish) but cannot find the relevant role for Viewer or Creator.

**Comment by shinchris** [comment]
Which version of Tableau Server are you using?

**Comment by elambrou5** [comment]
@shinchris , I am using 2018.3

**Comment by shinchris** [comment]
I think the issue may be due to the REST API version you are using. When you instantiate the `Server` object in your script, you can pass in a flag to have it automatically use the appropriate REST API version for your Tableau Server instance. See docs here: https://tableau.github.io/server-client-python/docs/versions#use-the-rest-api-version-supported-by-the-server

Also note that for REST API 3.0 and later (2018.3 is on REST API version 3.2), the site_role can be one of the following: Creator, Explorer, ExplorerCanPublish,  ReadOnly, SiteAdministratorCreator, SiteAdministratorExplorer, UnlicensedWithPublish (https://tableau.github.io/server-client-python/docs/api-ref#users). The library has enums for all of these site roles in `user_item.py`.

Please reopen this issue if you still run into problems with site roles.
