### ISSUE TITLE
Tableau delete site not working

### ISSUE THREAD

**Issue by saggarsunil** [tableau/server-client-python#501]
I am trying to automate Tableau site creation and deletion using python APIs. https://tableau.github.io/server-client-python/docs/

I am using admin account for this operation. However, when i try to delete site, i get the following error

User 'admin' is authenticated for site '9f086a43-e50f-4c19-85c6' and may not access or modify resources on site 'efbea3a6-17e9-4383-b4c5'.

'9f086a43-e50f-4c19-85c6' -- > default Site

'efbea3a6-17e9-4383-b4c5' --> I want to delete this site

I believe admin should have all the rights to delete or modify the site. From the error, it is obvious that it is an authorization issue. Why is admin not allowed to delete this site ?

**Comment by dzucker-tab** [comment]
@saggarsunil 

You have to sign in to the site in order to delete it. From: 

https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_sites.htm#delete_site

"Note: You must have previously called Sign In and signed in to a site in order to delete the site. (When you call this method, you must include the authentication token that you got back when you signed into the site.)"

You'll need to use the site's contentURL (name of the subpath following `/sites/` in the browser bar when you browse to your server) in the sign in request body.

hope that helps

**Comment by dzucker-tab** [comment]
An alternative is to switch to the to be deleted site using Switch Site once you are signed in to default:

```
POST /api/api-version/auth/switchSite
```
Request Body

```
<tsRequest>
   <site contentUrl="SITE_TO_BE_DELETED_CONTENTURL" />
</tsRequest>
```
