### ISSUE TITLE
Clarify that adding tags requires a list

### ISSUE THREAD

**Issue by benlower** [tableau/server-client-python#52]
When calling tags.update("foobar") the result is the workbook being tagged with five tags: 'f', 'o', 'b', 'a', 'r'.  To get the expected behavior you have to use tags.update(["foobar"]) because it expects a list. Clarify this.

**Comment by t8y8** [comment]
I researched a few options:

1. Check the tag_set, if it's a string, convert it to a list of one silently to the user doesn't have to think about it
2. Check the tag_set, if it's not an iterable (except for string), throw an exception
3. Do nothing, doc it more clearly.

It looks like the current implementation relies on sets so that it can determine if a workbook already has tags or not, and can compute the difference

**Comment by LGraber** [comment]
For what he did, do nothing and doc since he called "update" on the set. If we want to, we can handle the case where the user assigns a value to "tags" which is a string or a list and convert it to a set instead of getting upset with them

**Comment by Talvalin** [comment]
I've been having a crack at this, and I'm a bit stuck. 

Whilst it's simple enough to add a setter to _workbook_item_ that checks for a string and then calls `workbook.tags.add`, there's nothing to stop someone from calling tags.update directly (ie: `workbook.tags = 'foobar'`), which then leads us back to the original reported issue.

Am I overthinking this? Is there a straightforward way of resolving the issue?

**Comment by irwando** [comment]
Docs are updated.
