### ISSUE TITLE
tableauserver client installation error

### ISSUE THREAD

**Issue by vinothdakshin** [tableau/server-client-python#556]
ERROR: Could not find a version that satisfies the requirement requests<3.0,>=
2.11 (from tableauserverclient==0+unknown) (from versions: none)
ERROR: No matching distribution found for requests<3.0,>=2.11 (from tableauserve
rclient==0+unknown)

getting the aforementioned error while trying to install Tableauserverclient thru PIP install command.
My server is Airgapped, no internet connection hence i am doing offline installation.

**Comment by bcantoni** [comment]
@vinothdakshin coming back to this issue, did you ever solve it?

If your installed version of Python does not include it, and since you are airgapped, you'll probably need to download and install requests manually: https://pypi.org/project/requests/

Also by the way, this library is officially only supported for Python 3.5 and up, so if you are on Python 2.x you should probably upgrade.

**Comment by bcantoni** [comment]
I'll go ahead and close this one. If the problem still exists, please reopen with comments.
