### ISSUE TITLE
Tableu Server client error : (401001: Signin Error ,Error signing in to Tableau Server)

### ISSUE THREAD

**Issue by imondal** [tableau/server-client-python#583]
Hi Everyone,
I am using Tableau Server client. I am trying to login to the server with the python tableau server client but I cannot get past the Log in. Here is what i am trying to run just to test access.

```
import tableauserverclient as TSC
server = TSC.Server("https://tableaublahblah .com")
server.add_http_options({'verify': False})
tableau_auth = TSC.TableauAuth("MyUserID","MyPassword",)
server.auth.sign_in(tableau_auth)

with server.auth.sign_in(tableau_auth):
    all_datasources, pagination_item = server.datasources.get()
    print("\nThere are {} datasources on site: ".format(pagination_item.total_available))
    print([datasource.name for datasource in all_datasources])
```

I am getting this error:
```
401001: Signin Error
    Error signing in to Tableau Server
```

I am using Tableau server 2019.3 and I am able to login to the server from web ui using the username and password.

Please suggest How can I fix this issue.

**Comment by yrfg** [comment]
use `http` instead of `https` at `TSC.Server()`
it worked for my code

**Comment by yrfg** [comment]
https://github.com/tableau/server-client-python/issues/325#issuecomment-462948146

**Comment by bcantoni** [comment]
It doesn't look like the same as issue 325 because that one covers a 405 error.

@imondal this is an older issue but are you still having problems? If the username/password are in fact working through the web UI to the same server, it's possible you don't have access to the default site and would need to include a sitename in  `TSC.TableauAuth` ([docs](https://tableau.github.io/server-client-python/docs/sign-in-out)).
