### ISSUE TITLE
How to Add Connection Credentials to Publish Workbook

### ISSUE THREAD

**Issue by geordielad** [tableau/server-client-python#63]
I have a workbook with an embedded live connection. On publish I need to add the credential password otherwise the publish fails. This implies that Embed is defaulting to true but I don't want to prompt anyway.

**Comment by t8y8** [comment]
@benlower bumped into this recently.

We don't currently have a way to set or embed connectionCredentials. 
It's technically an option of the publish, so it might be natural to add it as a parameter.

If you're interested in submitting a patch the places to start would be:
* tableauserverclient/server/endpoint/workbook_endpoint.py
* tableauserverclient/server/request_factory.py

I did a quick and dirty hack for Ben to test something, but it was hard-coded and inelegant... It just added a `connectionCredentials` element to the request serializer in request_factory.py always.

**Comment by bryantbhowell** [comment]
This is not an enhancement it is a bug that needs to be fixed. This cripples the usefulness of the library for publishing. The only connection type that can publish without credentials is SQL Server with Windows Auth, which is not the most common situation in a SaaS / multi-tenant deployment.

**Comment by benlower** [comment]
@bryantbhowell thanks for the additional feedback. i'm changing this back to enhancement because that fits our definition ( @RussTheAerialist just clarified things better in [contributing.md](https://github.com/tableau/server-client-python/blob/master/contributing.md) ).

if this is critical for you, please add the 'Critical' label and we will prioritize. 'cripples' seems a bit overstated here but we get the importance ;)

**Comment by t8y8** [comment]
@geordielad would you be able to post the PR that you shared with me offline? 
I think you were pretty close, even if we need to help out with some of the testing parts.

**Comment by RussTheAerialist** [comment]
This was implemented by @geordielad in #80
