### ISSUE TITLE
Sign In through trusted ticket

### ISSUE THREAD

**Issue by neemagaurav1996** [tableau/server-client-python#663]
I want to sign in from trusted ticket through API. Is there any way or workaround to do this? There is nothing mentioned in the API related to this.

**Comment by RussTheAerialist** [comment]
Trusted tickets are based on the wg_session cookie. You can take the value of the wg_session cookie that is generated as a result of the trusted ticket, and put that in the X-Tableau-Auth header.  This isn't supported directly in TSC, but as a work around, once you create the server object, you can do `server._auth_token = wg_session` where the wg_session variable is set after you've done the trusted tickets dance.

**Comment by neemagaurav1996** [comment]
What am I missing here? I have another code to generate the trusted token. Do you have any snippet that you can share?

```
import tableauserverclient as TSC

server = TSC.Server('<SERVER_NAME>')
server._auth_token = '<TRUSTED_TOKEN>'
print(server.sites.get())
```

**Comment by RussTheAerialist** [comment]
You can’t use trusted tickets like that. You need to redeem the trusted
ticket for a session by hitting a url for the viz, which will create your
session and you can grab the wg_session cookie from the response.

It’s not guaranteed to work because it’s not officially supported, but
that’s the only workaround that I think might work. We’ve never tried it
because trusted tickets are designed specifically for viz viewing, but
general login.

Ideally, you’d migrate to using Personal Access Tokens for the users who
need to access the rest api.

**Comment by neemagaurav1996** [comment]
@RussTheAerialist I understand the consequences of using trusted tickets. I am migrating to Personal Access Tokens for now. Thanks for your support.
