### ISSUE TITLE
How can I update workbook/worksheet colors

### ISSUE THREAD

**Issue by caffeinatedMike** [tableau/server-client-python#666]
I can't find any documentation of using the API to update "metadata" aspects, such as fonts for specific workbooks or worksheets. Can someone provide a sample snippet that accomplishes this?

What I'm trying to do is iterate over all  elements of each worksheet in a workbook and change the color. Since changing the color palette after initially creating a workbook doesn't retroactively change any elements created before the color palette change this is the solution I'm trying to implement.

**Comment by RussTheAerialist** [comment]
The functionality you need is not available in the rest api. In general, we
do not allow you to edit the workbook programmatically at this time.
Anything that is encoded in the workbook document itself (like font and
color palettes) are not editable via an api, we do not currently have plans
to allow such editing.

As a workaround, you can download the workbook, and since the twb file is
xml, you can modify the xml programmatically, and then republish the
workbook.

This does assume that you have user and password for all data sources
associated with the workbooks you are modifying because you will need those
to republish. Also note that we do not guarantee that the twb file format
will not change between release.

**Comment by caffeinatedMike** [comment]
I was afraid of that 😔 I did find an python module to make edits to the twb files, so I guess my only remaining question is can the twb files be downloaded via the API?

**Comment by RussTheAerialist** [comment]
Yes you can! It’s the download endpoint for workbooks.  You can find the
docs here:
https://tableau.github.io/server-client-python/docs/api-ref#workbooks

Search that page for workbooks.download for info on how to download them.

**Comment by caffeinatedMike** [comment]
Thanks!
