### ISSUE TITLE
server.jobs.get_by_id failing inconsistently with 401002: Unauthorized Access error

### ISSUE THREAD

**Issue by quenchua** [tableau/server-client-python#693]
Hello,

I am writing a python script to trigger and monitor extract refreshes for a given set of datasource IDs.

First, I trigger the refresh using `server.datasources.refresh(datasource)` for all the given datasource IDs using multi threading.
Then, I monitor the progress of these refreshes and print out a message accordingly.
Do note that my Tableau server is configured to run only 2 extract refreshes at once, all others go into a pending state.

But, what I'm seeing is that every once in a while, one of the threads will throw a 401002 error when checking the status of the refresh job. Here's my code snippet:

```
def monitor_refresh_progress(self, job_id, datasource):
    # Get initial job status value, will be -1 if in progress
    with self.server.auth.sign_in(self.tableau_auth):
        job_status = self.server.jobs.get_by_id(job_id)
    # Keep polling until success or failure, added random to avoid multiple simultaneous hits
    while int(job_status.finish_code) not in [0,1]:
        time.sleep(randint(110,130))
        with self.server.auth.sign_in(self.tableau_auth):
            job_status = self.server.jobs.get_by_id(job_id)
    if int(job_status.finish_code) == 0:
        self.logger.info("Extract Refresh successfully completed for datasource: {}".format(datasource.name))
    else:
        slack.post_message(text=":: ERROR :: Tableau Extract Refresh failed for datasource {}.".format(datasource.name))
        self.logger.error("Extract Refresh failed for datasource: {}".format(datasource.name))
        raise Exception("Extract Refresh failed for datasource: {}".format(datasource.name))
```

Right now, I have added a retry decorator for this monitor_refersh_progress() method but I'm not too sure about the efficacy since I'm using multi threading.

Am I doing something wrong? Any help would be appreciated.

Thanks

**Comment by shinchris** [comment]
Hi @quenchua, the 401002 in this case most likely means that the auth token generated by the sign_in call is invalid. I'm not sure what would cause those tokens to be invalid, though, since you call sign_in before getting get_by_id().

I have a couple of suggestions to see if we can figure out what's going on:
1. Start logging the TSC calls to server to see if it contains anything interesting. You can do it by adding the below snippet to the top of your script.
```python
import logging
logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', filename="tsc.log", level="DEBUG")
```
2. You can probably reduce the number of sign_in calls you make. For example, you can move the while loop inside of the sign_in context manager.

Other than that, have you looked into using [Webhooks](https://github.com/tableau/webhooks-docs)? Webhooks can be configured so that when a datasource refresh job is completed, it will automatically send a [slack message](https://github.com/tableau/datadev-hackathon/wiki/Send-a-Slack-notification-when-a-workbook-is-updated).

**Comment by quenchua** [comment]
Hello @shinchris, thanks for the suggestions.
For now, the retry decorator seems to be working.

I will look into Webhooks in the future.

**Comment by shinchris** [comment]
I'll close this issue for now. Please reopen if the issue comes up again.

**Comment by robmarkcole** [comment]
@shinchris I also am experiencing this error, and it does appear to occur only once a task has been running for a while, so assume it must be related to a token ageing

**Comment by VDFaller** [comment]
@shinchris is it possible this is due to multiple opens and closes in a row?  I am trying to come at this multiple ways so I have an [SO issue](https://stackoverflow.com/questions/76060220/nested-function-calls-using-with-statements-for-authentication?noredirect=1#comment134146922_76060220) as well.  Also it seemed to only start after we started using PAT instead of UID/PWD.
