### ISSUE TITLE
Resource ID for view?

### ISSUE THREAD

**Issue by msrinathr** [tableau/server-client-python#697]
Hi, 
I am using server-client-python to connect to my site and export the view as PDF using the export.py file in samples.
One of the parameter is resource ID, how to find for the view? The view URL doesn't have the long alpha numeric ID.

Thanks,

**Comment by shinchris** [comment]
Hi @msrinathr, in order to get the resource ID, you will first have to use the [views.get()](https://tableau.github.io/server-client-python/docs/api-ref#views) method to get the view items that contain the IDs. You can also use filters with the views.get() method to narrow down the results returned from the API.
