### ISSUE TITLE
Updated datasource connection to do sql authentication, looks good on server but when downloaded datasource connection is still windows auth

### ISSUE THREAD

**Issue by Grontarg** [tableau/server-client-python#747]
I am having a problem where I want to change from a windows auth to a sql auth in a Tableau datasource.  It seems fine when I look at it from the server site (has embedded password and has the right name/pw) but when I download the datasource and go to edit connection, the uname/pw i updated to is no longer present and it is set to windows authentication.
Is there any way where I can have reserve the sql authentication name/pw i set it to when after I download the datasource?

```
import tableauserverclient as TSC
tableau_auth = TSC.TableauAuth('**myUsername**', '**myPassword**')
server = TSC.Server('**servername**')
with server.auth.sign_in(tableau_auth):
    ds = server.datasources
    
    update_function = ds.update_connection
    resource = ds.get_by_id('35f2c541-444e-4cbf-aa34-5096f01682c5') 
    connections = ds.populate_connections(resource)
    resconn = resource.connections
    resconn0 = resconn[0]

    resconn0.server_address = '**updatedServerName'**
    resconn0.username = '**updatedUserName**'
    resconn0.password = '**updatedPassword**'
    resconn0.embed_password = True
    resconn0.server_port = None
    
    update_function(resource, resconn0)
```

what it looks like after the update
![image](https://user-images.githubusercontent.com/37784243/100916657-a6538a00-349b-11eb-8c1a-6a43b3bf1dcf.png)

what it looks like when i download and go to edit connection (updated server name is present in here)
![image](https://user-images.githubusercontent.com/37784243/100917724-25958d80-349d-11eb-86ca-c809b30008a6.png)

Is there anything I need to change or am forgetting here?  I am admin and the update went through w/no errors but did not work as expected.

**Comment by cpatrick725** [comment]
@Grontarg  I ran into this issue as well. It does not appear the REST API can change the authentication type. The Windows authentication type is stored as "sspi" in the Connection information in the .TWB. To change to SQL User I had to modify the XML of the TWB to set authentication type to "sqlserver". I used TSC to download the workbook, then got the .TWB locally, updated the XML, and republished.

When republishing it was required to also include a TSC Connection Credential object with the workbook item, with Embed=True, for the credentials to persist on upload. 

Need to clean up my script more but could post a sample if needed.

**Comment by Grontarg** [comment]
@cpatrick725 Thanks for the response.  Is this not a bug?  I was hoping I wouldn't have to download every TWB and run these manual changes. If you could post a sample I would appreciate that just in case I'm misunderstanding something.

**Comment by cpatrick725** [comment]
I don't think it's a bug since you can't embed credentials with Windows authentication, so the authentication type is taking precedence over the embed flag. Perhaps an error or warning could be thrown, but I do think it's functioning as expected. Would love to be wrong though.. :) 

This sample file is a bit choppy as I pulled it from a larger workbook update process. Also this is for updating connections inside a workbook, and not a .TDS. But would imagine it'd be similar to do the same process against a TDS. There are a few places where the server and database names are hardcoded, be sure to check/change.

The magic here is changing the "authentication" attribute on the Connection XML object, and setting the credentials to Embed=True on publish.

Original:
![image](https://user-images.githubusercontent.com/70548277/100943687-8d0a0800-34b2-11eb-9352-fff9a1f43862.png)

Updated:
![image](https://user-images.githubusercontent.com/70548277/100943795-c478b480-34b2-11eb-986d-18282d719c97.png)

[tsc_download_modify_publish_SAMPLE.py.txt](https://github.com/tableau/server-client-python/files/5632663/tsc_download_modify_publish_SAMPLE.py.txt)

**Comment by bcantoni** [comment]
I'm going to close based on the discussion and the workaround provided by @cpatrick725.
