### ISSUE TITLE
server.users.get() returns error if you have Guest user enabled

### ISSUE THREAD

**Issue by Kovner** [tableau/server-client-python#79]
If you have guest user enabled, it's site_role is "Guest", if you call server.users.get(), you get an error "ValueError: Invalid value: Guest. site_role must be of type Roles."
Presumably, this is because tableauserverclient.Roles does not include "Guest", but not sure if the solution is to ignore guest in get() or to include "Guest" in Roles.

**Comment by t8y8** [comment]
I recommend: add `Guest` to the siteRole enum and block it in the setter, since you can't create a 'Guest' just read them.

**Comment by geordielad** [comment]
Is it not useful to get the the guest user so you can set permissions for the guest user, or remove/add them to a group etc.?

**Comment by t8y8** [comment]
Oh absolutely. We need to fix that.

But the challenge is that you cannot 'create' a Guest user, so adding or updating a user to that site role is invalid, and it's a little tricky for the UserItem to know where it's going to be used. 

I think I propose to not let the model care, and the Server can throw an appropriate error if you try and set a user to a  'Guest' role. I'd be curious what the other folks on the core team think -- but it feels the cleanest to me.

(In which case the fix is a one-liner, add 'Guest')

**Comment by LGraber** [comment]
Generally speaking, that is our method ... let the server error when it errors instead of trying to duplicate the error checking (with some rare exceptions). As to adding the Guest role, that seems pretty reasonable. I am fine I think with the one line fix. I would say start with that. I don't love it, though, as the mechanism for discovering that Guest access is enabled. We need a better mechanism for discovering some of those properties.

**Comment by RussTheAerialist** [comment]
👍 what @LGraber said.

**Comment by t8y8** [comment]
Awesome.. @Kovner do you want to submit a PR?

**Comment by RussTheAerialist** [comment]
Looks like this was fixed by #83

**Comment by geordielad** [comment]
@LGraber can you elaborate on 

>  I don't love it, though, as the mechanism for discovering that Guest access is enabled. We need a better mechanism for discovering some of those properties.

Could we do a helper until there is direct support in the REST API? Suppose we had a IsGuestEnabled function. It would figure out True or false by doing a server.users.get() (with a filter - so its efficient). Assuming the guest is enabled get will return a value if not enable then it does not return a value (I am assuming this is the behavior from @Kovner 's initial issue.) In the future an explicit REST API endpoint might become available ?server_settings site_settings. We would then refactor the helper. Is this a valid approach generally?

**Comment by t8y8** [comment]
It's a site setting, and should be returned/checkable there

**Comment by LGraber** [comment]
What Tyler said is what I meant ... we should have a way to access them. Doing it by checking for Guest from the users endpoint is a sample. It is not something we would add to our core API.
