### ISSUE TITLE
Unauthorized Access error while calling populate_image()

### ISSUE THREAD

**Issue by rr-hari-prakash** [tableau/server-client-python#830]
**Describe the bug**
While looping through list of tableau views to populate image (after applying view filters), first few images are getting populated but after like 6th image, its throwing the following error,
`401002: Unauthorized Access
                Invalid authentication credentials were provided.`

NOTE: I'm using PersonalAccessTokenAuth to login

**To Reproduce**
```
for view in views:
  if view.name == viewname:
      self.server.views.populate_image(view, image_req_option)
      file_name = '%s.png' % (view.name.lower().replace(' ', '') + '_' + str(uuid4()))
      path = img_path / file_name
      with open(path, 'wb') as f:
          f.write(view.image)
      return str(path)
  else:
      path = ''
      pass

```
**Results**
What are the results or error messages received?
```
`File "/var/task/tableauserverclient/models/view_item.py", line 57, in image
    return self._image()
  File "/var/task/tableauserverclient/server/endpoint/views_endpoint.py", line 76, in image_fetcher
    return self._get_view_image(view_item, req_options)
  File "/var/task/tableauserverclient/server/endpoint/views_endpoint.py", line 83, in _get_view_image
    server_response = self.get_request(url, req_options)
  File "/var/task/tableauserverclient/server/endpoint/endpoint.py", line 95, in get_request
    return self._make_request(self.parent_srv.session.get, url,
  File "/var/task/tableauserverclient/server/endpoint/endpoint.py", line 57, in _make_request
    self._check_status(server_response)
  File "/var/task/tableauserverclient/server/endpoint/endpoint.py", line 71, in _check_status
    raise ServerResponseError.from_response(server_response.content, self.parent_srv.namespace)
tableauserverclient.server.endpoint.exceptions.ServerResponseError: 
```

        401002: Unauthorized Access
                Invalid authentication credentials were provided.`

**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by jacalata** [comment]
I've seen this message when a user ends up with multiple connections for the same PAT. I can't immediately see how this might be happening with your code, so that might not be the answer. 

If this is still an issue, can you tell us if you're using Tableau Online, or what version of Server you're running on?

**Comment by alexandruandrei90** [comment]
To add to what @jacalata said. I am experiencing the same when firing multiple cron jobs at the same time which use the same token. The first one works, but the others fail with a `401002`. The solution seems to spread out the cron jobs.

Interestingly, within each job I am looping through multiple objects to populate csvs, but that has never been an issue.

**Comment by bcantoni** [comment]
@alexandruandrei90 what you're likely seeing is the expected behavior. When you log in to Tableau Server with a PAT, the TSC library receives an auth token which it uses for subsequent REST calls. If that same PAT is used again, the first auth token will become invalid and future REST calls using it will fail.

One way you could work around this would be creating multiple PAT for different purposes. For example if you had 3 cron jobs running at different intervals, you could create PAT1/PAT2/PAT3.
