### ISSUE TITLE
Sample file missing 

### ISSUE THREAD

**Issue by ejoynes** [tableau/server-client-python#905]
This page,  https://tableau.github.io/server-client-python/docs/samples#samples-list , has metadata_query.py in the list of sample files, but it doesn't exist in the repo at https://github.com/tableau/server-client-python/tree/master/samples

**Comment by bcantoni** [comment]
@ejoynes thanks for catching that. That sample file was recently added and will be part of the next TSC release. (The docs were already updated, so that made it confusing.) Until the next release, you can find that file on the development branch here:
https://github.com/tableau/server-client-python/blob/development/samples/metadata_query.py

**Comment by vogelsgesang** [comment]
Nice to see that the docs are actually getting read and that there is interest in the example for metadata queries :)
Sorry for the confusion, though!

**Comment by jacalata** [comment]
Released in https://github.com/tableau/server-client-python/releases/tag/v0.17.0
