### ISSUE TITLE
403132 error when publish twb file

### ISSUE THREAD

**Issue by alexandrebfaust** [tableau/server-client-python#972]
I'm trying to publish a .twb workbook cause I can change the database name variable inside xml file, but everytime returns error , already tryed skip_connection_check=True.
403132: Failed connection check	One or more data sources used by the workbook could not be reached

```
with server.auth.sign_in(tableau_auth):
   # create a workbook item
   wb_item = TSC.WorkbookItem(name='Contracts', project_id='b42fe4fc-b954-453e-b5a9-2943be65a680')
   # call the publish method with the workbook item
   wb_item = server.workbooks.publish(wb_item, './Contracts/Contracts.twb', 'Overwrite', skip_connection_check=True)
```

**Comment by amartincolville** [comment]
Hi @alexandrebfaust 
Maybe it is work you check the [WorkbookItem](https://tableau.github.io/server-client-python/docs/api-ref#workbooks) `connections` argument, to check if your connection is not matching to the one found on the Tableau Server. you can use the `populate_connections` to add the correct `ConnectionItem` objects.
Furthermore, it may be best if you do not reset de `wb_item` variable, but create a new variable in the call, as this may mess up the variable the code is referencing.

**Comment by jacalata** [comment]
Hi @alexandrebfaust  - changing the database name by hand might not work, because there are lots of related pieces. Perhaps you could try using the document api tool? Here's a sample that shows creating a workbook and setting the db name - https://github.com/tableau/document-api-python/blob/master/samples/replicate-workbook/replicate_workbook.py

**Comment by jacalata** [comment]
closing as stale.
