### ISSUE TITLE
Proposal: Auto-Detect API Version via ServerInfo

### ISSUE THREAD

**Issue by t8y8** [tableau/server-client-python#99]
We could perform an auto-detect step under sign_in to set the highest API version supported (with an override) now that SeverInfo is in 10.1

**Comment by RussTheAerialist** [comment]
We discussed this previously, but what do we do with versions of the API that are less than 2.4?

**Comment by t8y8** [comment]
I was just adding in some psuedo code, but a simple try/except block seems fine.

````
try:
        version = self._find_highest_supported()
except ServerVersionNotSupported:
        version = '2.3'
`````

We can have the `_find_highest_supported() call try against 2.4 and throw a very specific exception if the call to serverinfo fails with a 404 or whatever the exact code it. We could even peek into the error detail code

**Comment by LGraber** [comment]
Sorry ... what are you trying to solve? You are trying to provide insight into what is the version of the REST api which is supported? If the server_info doesn't work, 2.4, right?

**Comment by t8y8** [comment]
Once @RussTheAerialist has the decorators that enable/disable endpoints based on version, the library should auto-detect the versions supported by the Server, right now we default to 2.3.

Which actually means that by default, someone will try to call ServerInfo, and it'll fail because 2.3 doesn't support that call.

**Comment by t8y8** [comment]
Alright, here's a diff that implements what I'm thinking but it has problems:

- Not sure where to put the exception so that it's plumbed to the right places
- It breaks all the tests because every Server instantiation now tries to call the server_info endpoint (But that can be fixed a few ways)
- Crude, but effective, and I think clean :P

[patch.txt](https://github.com/tableau/server-client-python/files/573521/patch.txt)

**Comment by LGraber** [comment]
I don't want to do this. The only thing I want to add is that by adding a version# decorator to methods:
a) They are a self documenting
b) If the user sets the server.version to a number earlier than that we can chose to short circuit and give an error instead of actually hitting the server.

I don't like the idea of making these server_info calls all the time. Russell didn't seem to be excited to do this either. Please explain what gain we get over what I listed above.
Thanks. See you tomorrow. :)

**Comment by t8y8** [comment]
Let me turn it around.

Without something like this, how do we expect our users to set the version of the API on Server?

**Comment by LGraber** [comment]
This would imply that as new versions of our server are released and subsequently deployed by our customers ... there scripts would potentially start acting differently without them changing anything including installing a new version of the library. We should possibly even be recommending that our customers set the value themselves since we may chose to change the default one day which would affect an upgrade. If we wanted to provide a utility to wrap server_info.get and subsequently set the server version, we can and tell people to call it before using the server if this is what they want but doing it automatically ... I am not yet sold.

**Comment by t8y8** [comment]
Applications may need to deal with different Servers, not just hard-coded to one.

This was a frequent request of partners like Interworks, who need to know the version of Server they're speaking to because they're wrapping the SCL in some sort of larger toolchain.

I'm not trying to sell you now, I'm just asking what your plan is.

If you, today, install the SCL, set up a `TSC.Server` and try to call `server_info.get()` you will get an exception, even against a 2.4 Server, because we hard code the version to 2.3, and that's not compatible. You have to know you're on a 2.4 Server to make to call to find out if you're on a 2.4 Server... That feels pretty user-unfriendly

**Comment by LGraber** [comment]
Someone who writes a big tool will almost certainly call server_info.get on their own to enable or disable features of their tool. I am not sure what doing it automatically for them adds.

Handling the exception from server_info. get which indicates that the version is "older", we can discuss whether we want to return something other than an exception since we technically got some information, just not exactly.

The question really is do we:
1) Hardcode the server version to the latest version that is released and say to customers .... if you are using an earlier version, you should set it explicitly
2) Default to auto-detect and have the user override.

Lets talk later. Like I said, I think there are cases where 2 will cause peoples scripts to potentially break when they were not expecting. However, I can also understand your points for how should the user pick and can see how 2 would be potentially quite helpful. I need to go to sleep.

**Comment by RussTheAerialist** [comment]
dang it, y'all, I was hoping I could put this off until Austin and talk in person, but I guess not.

Okay, here's my opinion on this.  Most of the functionality of this library favors explicit over implicit calling of the server (Pager is an exception).  To make it explicit-enough while still user friendly, could we have a server method called something like "use_server_version" which fetches the server info (or the other place to get it if server info doesn't exist).  In this method, we could automatically set the version to 2.4, and only if the version is less than 2.4 would we get an exception.  And it's explicit about setting the version of the server to whatever the server returns.

I agree that the default version should probably be in lock-step with the product version as much as possible.  We are in a limbo state currently because 10.1 didn't come out before we cut 0.2 even through 0.2 has features to support 10.1.  I could make a 0.2.1 to correct it (though, hrm, is it a bug fix?)

**Comment by RussTheAerialist** [comment]
I should also mention that this feels like a few separate issues to me:

- We have not updating the default version number to be the latest released version of the rest api.
- We need some user-friendly way to set the version number to whatever the server supports.
- #55 - Decorate the calls so you know which version you need.

**Comment by t8y8** [comment]
I can respect the design decision to "Prefer explicit over implicit" but we should make sure to consider the amount of boilerplate that could be required for the 'average use case' and weigh that against other design considerations.

Adding another function that I predict will get called most of the time could be too much -- but I could be wrong and it's totally fine. Alright, my objection filed :)

@RussTheAerialist in direct response: something like that seems reasonable overall... but we can't default to the *latest* version, can we?

Since all API calls get constructed off the Server version, it'll try 'Sign In' on that API version -- that means anyone who pip installs the latest TSC but hasn't upgraded their Server will start their API journey with an error -- that feels very aggressive.

**Comment by cs905s** [comment]
Input as an end user from the hackathon:
There is a catch 22. To get the API version or server version - you need to use the server_info API. However this API is only available from 2.4. If I am writing a REST call to an unknown Tableau server - I can't figure out the API version in advance (i.e. hardcoded). So it would be great for the API to self configure.

**Comment by RussTheAerialist** [comment]
@t8y8 this is done, right?  If so, please close this?

**Comment by t8y8** [comment]
Pretty close, we don't do it *automatically* quite yet, you still have to call `use_highest_version` and I still vote one last time for making it work automagically :)
